require('dotenv').config(); // Load environment variables from .env file
const express = require('express');
const cors = require('cors'); // Middleware to enable Cross-Origin Resource Sharing
const multer = require('multer'); // Middleware for handling multipart/form-data (file uploads)
const sharp = require('sharp'); // High-performance Node.js image processing library
const FormData = require('form-data'); // For creating multipart/form-data requests
const axios = require('axios'); // Promise-based HTTP client for the browser and node.js

const app = express();
const port = 5000;

app.use(cors()); // Enable CORS for all routes
app.use(express.json()); // Parse JSON request bodies

// Configure multer to store uploaded files in memory as a Buffer
const upload = multer({ storage: multer.memoryStorage() });

// API endpoint for generating the poster
app.post('/api/generate-poster', upload.single('image'), async (req, res) => {
  try {
    const { name, organization } = req.body;
    const imageBuffer = req.file.buffer; // The uploaded image as a Buffer

    // --- Background Removal using remove.bg API ---
    const formData = new FormData();
    formData.append('image_file', imageBuffer, 'image.jpg'); // Append the image buffer
    formData.append('size', 'auto'); // Request automatic sizing for background removal

    const removeBgResponse = await axios.post(
      'https://api.remove.bg/v1.0/removebg',
      formData,
      {
        headers: {
          ...formData.getHeaders(), // Include headers generated by FormData (e.g., Content-Type with boundary)
          'X-Api-Key': process.env.REMOVE_BG_API_KEY, // Your remove.bg API key from .env
        },
        responseType: 'arraybuffer', // Expecting a binary response (the processed image)
      }
    );

    const imageWithoutBg = removeBgResponse.data; // The image data with background removed

    // --- Image Composition using Sharp ---
    // Load the base poster template and composite the elements onto it
    const poster = await sharp('../frontend/src/assets/poster-template.png')
      .composite([
        // Composite the user's image (without background) onto the poster
        { input: imageWithoutBg, gravity: 'northwest', left: 94, top: 307 },
        // Composite the user's name text
        {
          input: {
            text: {
              text: `<span foreground="white">${name}</span>`, // Text content with white foreground
              font: 'Ubuntu', // Specify font family
              rgba: true, // Enable RGBA output for transparency
              dpi: 72, // Dots per inch for text rendering
            },
          },
          top: 540,
          left: 94,
        },
        // Composite the user's organization/title text
        {
          input: {
            text: {
              text: `<span foreground="white">${organization}</span>`,
              font: 'Ubuntu',
              rgba: true,
              dpi: 72,
            },
          },
          top: 580, // Position below the name, adjust as needed
          left: 94,
        },
      ])
      .toBuffer(); // Output the final composite image as a Buffer

    res.set('Content-Type', 'image/png'); // Set response header to indicate PNG image
    res.send(poster); // Send the generated poster image
  } catch (error) {
    console.error('Error generating poster:', error);
    res.status(500).send('Error generating poster');
    // TODO: Implement more specific error handling and user feedback
  }
});

app.listen(port, () => {
  console.log(`Server listening at http://localhost:${port}`);
});
